# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_AEST) 	+= aest.o

aest-y		:= aest-core.o
aest-y		+= aest-sysfs.o
aest-y		+= aest-inject.o
aest-y		+= aest-cmn.o

obj-$(CONFIG_OF_AEST)   += aest-of.o
